### PR TITLE
Updated to 1.0.0

### PR DESCRIPTION
**Pull request by mtsokol**
Hi @softinio @mijicd !

Just updated to 1.0.0 version. Can we have next release after merging it?

### CODE REVIEW

**Comment by mtsokol** [comment]
Hmm linting phase fails with:
```
Downloading sbt launcher for 1.3.13:
  From  http://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.3.13/sbt-launch.jar
    To  /home/circleci/.sbt/launchers/1.3.13/sbt-launch.jar
Download failed.
```

**Comment by mijicd** [comment]
@mtsokol can you run it locally? It might be either a glitch or a stale version of sbt launcher.

**Comment by riosgabriel** [comment]
@mtsokol I think this #249 fix that problem

**Comment by mtsokol** [comment]
@mijicd hm `./sbt ++${SCALA_VERSION}! check` also fails locally for me (also for e.g. zio-keeper project).

**Comment by mtsokol** [comment]
@riosgabriel Thanks! Then it might need to be fixed across all zio org projects?

**Comment by mijicd** [comment]
@mtsokol i find it odd for keeper, as we're running it actively and it doesn't fail, but.. Glitches happen :).

**Comment by riosgabriel** [comment]
@mtsokol I think so. They changed all repositories urls to `https`

**Comment by softinio** [comment]
> @mtsokol I think #249 could fix that problem

@mtsokol Just merged above PR, rebase and lets see what happens

**Comment by mtsokol** [comment]
@softinio ok, now it works 😄. @riosgabriel thanks once again for solution!

**Comment by softinio** [comment]
Linting still a problem

**Pull request merged**
